export const PARTIES = [
  { slug: "bjp", title: "Bharatiya Janata Party" },
  { slug: "congress", title: "Indian National Congress" },
  { slug: "aap", title: "Aam Aadmi Party" },
  { slug: "tmc", title: "All India Trinamool Congress" },
  { slug: "sp", title: "Samajwadi Party" },
  { slug: "dmk", title: "Dravida Munnetra Kazhagam" },
  { slug: "aiadmk", title: "All India Anna Dravida Munnetra Kazhagam" },
  { slug: "tdp", title: "Telugu Desam Party" },
  { slug: "jdu", title: "Janata Dal (United)" },
  { slug: "rjd", title: "Rashtriya Janata Dal" },
  { slug: "bjd", title: "Biju Janata Dal" },
  { slug: "ncp", title: "Nationalist Congress Party" },
  { slug: "shivsena", title: "Shiv Sena" },
  { slug: "ssubt", title: "Shiv Sena (Uddhav Balasaheb Thackeray)" },
  { slug: "ncpsp", title: "Nationalist Congress Party (Sharadchandra Pawar)" },
  { slug: "cpi", title: "Communist Party of India" },
  { slug: "cpm", title: "Communist Party of India (Marxist)" },
  { slug: "jmm", title: "Jharkhand Mukti Morcha" },
  { slug: "aimim", title: "All India Majlis-e-Ittehadul Muslimeen" },
  { slug: "agp", title: "Asom Gana Parishad" },
  { slug: "rld", title: "Rashtriya Lok Dal" },
  { slug: "ljprv", title: "Lok Janshakti Party (Ram Vilas)" },
  { slug: "vck", title: "Viduthalai Chiruthaigal Katchi" },
  { slug: "skm", title: "Sikkim Krantikari Morcha" },
  { slug: "zpm", title: "Zoram People's Movement" },
  { slug: "uppl", title: "United People's Party Liberal" }
];